### PR TITLE
SLING-11843 build on JDK11/17 with Windows and Linux by default

### PR DESCRIPTION
**Pull request by kwin**

### CODE REVIEW

**Review by enapps-enorman — APPROVED** [review]
I'm not sure how I would test this to make sure it works, but at first glance this LGTM.

**Review by rombert — COMMENTED** [review]
Pasting my comment from https://issues.apache.org/jira/browse/SLING-11843?focusedCommentId=17716604&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-17716604

Perhaps we should be a bit more specific regarding the Java version being used and not enable it when we know for sure it will fail. We know for a fact that parent pom 35 is required for Java 11, so let's only enable Java 11 builds for projects with have a recent enough parent pom version. I think we can make a similar statement for Java 17, so I propose we conditionally enable Java 11 and Java 17 based on the parent pom version.

**Comment by kwin** [comment]
Checking out the parent version is not that easy (IMHO the Jenkins library should not parse the pom.xml, also this would require resolving Maven properties). Also I consider all modules still on parent 35 or older basically unmaintained (so they don't need a working CI) and a failing build hopefully triggers the necessary update (which is crucial also for other reasons).

**Review by stefanseifert — APPROVED** [review]
i'm very looking forward to get in windows-builds by default, because it happens very often that unit test fail in windows environments and often i'm the only one who notices.

i agree with konrads comment that it should be fine to accept some failed builds on unmaintained modules, and take this as incentive to either fix or archive them.

**Comment by rombert** [comment]
Looks like I'm the only one reluctant to this change, so I won't veto it. It would be nice to have some communication on the dev list though, some module builds will start failing and fixing them would be a tough thing ( e.g. migrate to parent pom >= 35 to support Java 11 ).

**Comment by kwin** [comment]
Discussion happened in https://lists.apache.org/thread/6tgoq2995vhlonrww21n73xpw6gpg4q6.

**Pull request merged**
