### PR TITLE
SLING-9749 Enable profile "ci" during Jenkins build

### PR DESCRIPTION
**Pull request by kwin**
for both Sonar and regular Maven build

### CODE REVIEW

**Comment by rombert** [comment]
@kwin - wouldn't it be more obvious is the profile would be activated thorugh the parent pom by looking at an env variable that we know is always defined on Jenkins?

**Comment by kwin** [comment]
I would like to decouple parent from a specific CI (like Jenkins). That profile id can also be easily set with Github Actions, Travis CI, ... and whatever we may  use in the future.
A profile activation in parent is always a heuristic, while setting it in the underlying pipeline config is always deterministic.

**Review by rombert — APPROVED** [review]
Makes sense, thanks

**Comment by rombert** [comment]
Can you also please add a note about this to https://cwiki.apache.org/confluence/display/SLING/Sling+Jenkins+Setup when you merge?

**Pull request merged**
